import json, os
HERE = os.path.dirname(os.path.abspath(__file__))
PK = os.path.join(HERE, "out", "pack4")
T = json.load(open(os.path.join(PK, "tiles.json")))
div = json.load(open(os.path.join(HERE, "out", "divider.json")))
# Placement of the walker on each plate (plate px): hips over the painted figure's old hips.
# Soles at 82% of the day plate, level with the clinic figures, so the frame keeps floor under
# his shoes at every desktop height (2026-09-26; they were on the painted figure's line, 88%).
# The night placement puts the soles on the same SCREEN line as by day, at the same screen
# height (figH / plate width equal), given homehero.module.css's crop rules.
place = {"light": dict(hipX=1318, feetY=772, figH=427, horizon=600, drift=12),
         "dark": dict(hipX=1432, feetY=779, figH=449, horizon=652, drift=10)}
L = ["/* GENERATED by scripts/hero-walker/emit.py — see HeroWalker.tsx. Do not hand-edit the frame tables. */",
     "export type WalkScale = { src: string; scale: number; w: number; h: number; frames: readonly (readonly [number, number, number, number, number, number])[] };",
     "export type WalkTheme = {",
     "  plate: readonly [number, number];",
     "  box: readonly [number, number, number, number];",
     "  divider: { b: number; m: number };",
     "  hipX: number; feetY: number; figH: number; horizon: number; drift: number;",
     "  backdrop: { src: string; x0: number; w: number; h: number; ext: number };",
     "  grain: { src: string; top: number; w: number; h: number };",
     "  frameHipX: number; frameFloorY: number; framePpm: number; bodyH: number; stride: number;",
     "  root: readonly number[]; strikes: { right: number; left: number };",
     "  scales: { hi: WalkScale; lo: WalkScale };",
     "  /** The start frame as a still, placed in full-size frame px. */",
     "  poster: { src: string; x: number; y: number; w: number; h: number };",
     "  /** Per frame, x,y of each WALK_JOINTS entry in full-size frame px. */",
     "  joints: readonly (readonly number[])[];",
     "};",
     'export const HERO_WALK: Record<"light" | "dark", WalkTheme> = {']
JN = json.load(open(os.path.join(PK, "walk-light.json")))["jointNames"]
L.insert(1, "export const WALK_JOINTS = " + json.dumps(JN) + " as const;")
G = json.load(open(os.path.join(PK, "walk-light.json")))["gait"]
L.insert(2, "/** Gait events and phases measured on the rendered cycle (scripts/hero-walker/gait.py): per frame [left, right]. */")
L.insert(3, "export const HERO_GAIT = " + json.dumps({k: G[k] for k in ("phases", "phase", "stance", "cop", "angles", "pelvisY", "obliq", "events", "ic", "to")}, separators=(",", ":")) + " as const;")
for t in ["light", "dark"]:
    m = json.load(open(os.path.join(PK, f"walk-{t}.json"))); q = place[t]; b = T[t]
    W, H = (1672, 941) if t == "light" else (1759, 894)
    L += [f"  {t}: {{",
          f"    plate: [{W}, {H}], box: [{b['x0']}, 0, {W}, {H}], divider: {{ b: {div[t]['b']}, m: {div[t]['m']} }},",
          f"    hipX: {q['hipX']}, feetY: {q['feetY']}, figH: {q['figH']}, horizon: {q['horizon']}, drift: {q['drift']},",
          f"    backdrop: {{ src: \"/images/hero/walk/walk-{t}-backdrop.webp\", x0: {b['x0']}, w: {b['w']}, h: {b['h']}, ext: {b['ext']} }},",
          f"    grain: {{ src: \"/images/hero/walk/walk-{t}-grain.webp\", top: {b['floorTop']}, w: {b['grainW']}, h: {b['grainH']} }},",
          f"    frameHipX: {m['hipX']}, frameFloorY: {round(m['floorY'], 2)}, framePpm: {round(m['ppm'], 3)}, bodyH: {m['bodyH']}, stride: {round(m['stride'], 5)},",
          f"    root: {json.dumps(m['root'])},",
          f"    strikes: {{ right: {m['strikes']['RightFoot']}, left: {m['strikes']['LeftFoot']} }},",
          "    scales: {"]
    for tag in ["hi", "lo"]:
        s = m["scales"][tag]
        L.append(f"      {tag}: {{ src: \"/images/hero/walk/{s['src']}\", scale: {s['scale']}, w: {s['w']}, h: {s['h']}, frames: {json.dumps(s['frames'])} }},")
    ps = m["poster"]
    L += ["    },", f"    poster: {{ src: \"/images/hero/walk/{ps['src']}\", x: {ps['x']}, y: {ps['y']}, w: {ps['w']}, h: {ps['h']} }},",
          f"    joints: {json.dumps(m['joints'])},", "  },"]
L.append("};")
open(r"C:/Users/Anubha/Documents/website/GaitAI-main/GaitAI/src/data/hero-walk.ts", "w", encoding="utf-8").write("\n".join(L) + "\n")
print("ok")
