"use client";

/**
 * THE LANGUAGE LAYER — an open-weight model, in the visitor's own browser.
 * =============================================================================
 * Transformers.js (`@huggingface/transformers`, Apache-2.0) running a quantized
 * ONNX build of an Apache-2.0 instruct model on WebGPU. No inference API, no
 * API key, no Cloud Function, no per-question cost, and no question leaving the
 * tab.
 *
 * THE NUMBER THAT DECIDES THE DESIGN
 * Measured from the Hugging Face CDN, `q4f16` weights:
 *
 *   onnx-community/Qwen2.5-1.5B-Instruct     1 221 878 940 B  ≈ 1.14 GiB
 *   HuggingFaceTB/SmolLM2-1.7B-Instruct      1 108 730 338 B  ≈ 1.03 GiB
 *
 * A gigabyte is not a lazy-load. It is a download a person has to agree to —
 * on a phone it may be their month. So the model is OPT-IN behind a stated
 * size, and `extractive.ts` answers immediately meanwhile. The brief asked for
 * the model to load when the panel opens; it also asked for elegance and for
 * the visitor never to feel stuck, and silently pulling 1.1 GiB from someone
 * who asked a one-line question is neither. The consent is one press, the size
 * is on it, and the choice is remembered.
 *
 * WHAT RUNS WHERE
 *   retrieval  →  always local, always first, the source of truth
 *   generation →  local, optional, and only ever fed retrieved records
 *
 * The model is a WRITER, not a source. It never sees the corpus beyond the
 * handful of records retrieval selected, and `prompt.ts` forbids it from
 * adding anything they do not establish.
 */

/**
 * THE RUNTIME IS LOADED FROM ITS OWN CDN, NOT BUNDLED.
 *
 * Three reasons, in order of weight:
 *
 *  1. IT CANNOT BE BUNDLED HERE. `onnxruntime-web`'s WebGPU bundle uses
 *     `import.meta`, and Next 14's Terser pass over an emitted asset rejects
 *     it outright: "'import.meta' cannot be used outside of module code".
 *     Aliasing the package's web build past webpack's conditional-export
 *     resolution gets as far as that, and no further.
 *  2. IT SHOULD NOT BE. The runtime is ~9 MB unpacked. Bundling it puts a
 *     webpack chunk on the deploy for something only a visitor who opts into
 *     the model ever executes, and re-downloads it on every unrelated deploy
 *     whose bundle hash changes.
 *  3. THE WEIGHTS ALREADY COME FROM A CDN. 1.1 GiB cannot live in a GitHub
 *     Pages repository, so the model path already fetches from
 *     huggingface.co. Adding the runtime alongside it changes the set of
 *     origins involved by nothing.
 *
 * WHAT THIS DOES AND DOES NOT MEAN FOR PRIVACY. Fetching the runtime and the
 * weights tells those CDNs that a browser asked for a model — the same thing
 * any script tag tells any CDN. The QUESTION never leaves the tab: it is
 * matched against a corpus already in memory and generated by weights already
 * in memory. That is the claim the panel makes, and it stays true.
 *
 * Pinned to an exact version on purpose: `@latest` would let a third party
 * change the code running in a visitor's browser without a deploy here.
 */
const RUNTIME_URL =
  "https://cdn.jsdelivr.net/npm/@huggingface/transformers@4.2.0/dist/transformers.min.js";

type TransformersModule = {
  pipeline: (
    task: string,
    model: string,
    options: Record<string, unknown>,
  ) => Promise<unknown>;
};

/**
 * `webpackIgnore` keeps the bundler out of it entirely — no resolution, no
 * chunk, no Terser pass. The URL is fetched by the browser at the moment the
 * visitor asks for the model and never before.
 */
async function loadRuntime(): Promise<TransformersModule> {
  return (await import(/* webpackIgnore: true */ RUNTIME_URL)) as TransformersModule;
}

export type ModelId =
  | "onnx-community/Qwen2.5-1.5B-Instruct"
  | "HuggingFaceTB/SmolLM2-1.7B-Instruct";

export interface ModelChoice {
  id: ModelId;
  label: string;
  /** Measured `q4f16` ONNX weight size in bytes, for honest UI copy. */
  bytes: number;
  license: string;
}

/**
 * The candidates, with their real sizes.
 *
 * Qwen is the default because it is the one asked for first, and because at
 * 1.5B it is the smaller network of the two despite the larger file — the
 * difference is vocabulary, and Qwen's is much bigger. `scripts/ask-bench.mjs`
 * scores both on the site's own 25 questions; that measurement, not
 * reputation, is what should settle the default.
 */
export const MODELS: Record<ModelId, ModelChoice> = {
  "onnx-community/Qwen2.5-1.5B-Instruct": {
    id: "onnx-community/Qwen2.5-1.5B-Instruct",
    label: "Qwen2.5 1.5B Instruct",
    bytes: 1_221_878_940,
    license: "Apache-2.0",
  },
  "HuggingFaceTB/SmolLM2-1.7B-Instruct": {
    id: "HuggingFaceTB/SmolLM2-1.7B-Instruct",
    label: "SmolLM2 1.7B Instruct",
    bytes: 1_108_730_338,
    license: "Apache-2.0",
  },
};

export const DEFAULT_MODEL: ModelId = "onnx-community/Qwen2.5-1.5B-Instruct";

/**
 * Generation settings: as close to deterministic as a sampler gets.
 *
 * The answer must be reproducible and must not drift from the records, so the
 * temperature is low and the length is capped short. `max_new_tokens` at 300 is
 * about three tight paragraphs — the brief's own ceiling, and the panel is
 * 410px wide.
 */
export const GENERATION = {
  max_new_tokens: 300,
  temperature: 0.1,
  top_p: 0.9,
  repetition_penalty: 1.1,
  do_sample: true,
} as const;

export type Stage =
  | "idle"
  | "unsupported"
  | "downloading"
  | "initialising"
  | "ready"
  | "failed";

export interface ModelStatus {
  stage: Stage;
  /** 0–1 across the whole download, or null before the first report. */
  progress: number | null;
  /** What the visitor is told. Never a stack trace. */
  detail: string;
  device: "webgpu" | "wasm" | null;
}

/**
 * Is WebGPU actually usable?
 *
 * `'gpu' in navigator` is necessary and not sufficient — the adapter request
 * is what fails on a blocklisted driver, in a VM, or under a policy that
 * exposes the API and refuses adapters. So we ask for one.
 */
export async function detectWebGPU(): Promise<boolean> {
  try {
    const gpu = (navigator as Navigator & { gpu?: { requestAdapter(): Promise<unknown> } })
      .gpu;
    if (!gpu) return false;
    const adapter = await gpu.requestAdapter();
    return Boolean(adapter);
  } catch {
    return false;
  }
}

type Generator = (
  messages: { role: string; content: string }[],
  options: Record<string, unknown>,
) => Promise<Array<{ generated_text: unknown }>>;

let pipe: Generator | null = null;
let loading: Promise<Generator> | null = null;
let loadedId: ModelId | null = null;

export const modelReady = () => pipe !== null;
export const loadedModel = () => loadedId;

/**
 * Fetch and initialise the model. Idempotent, and safe to call again after a
 * failure — a failed attempt clears itself so a retry is a real retry.
 *
 * Progress is reported per file and aggregated: Transformers.js emits one
 * `progress` event stream per asset (weights, tokenizer, config), and reporting
 * the raw stream would show the bar restarting several times.
 */
export async function loadModel(
  id: ModelId,
  onStatus: (status: ModelStatus) => void,
): Promise<Generator> {
  if (pipe && loadedId === id) return pipe;
  if (loading) return loading;

  loading = (async () => {
    const webgpu = await detectWebGPU();
    const device: "webgpu" | "wasm" = webgpu ? "webgpu" : "wasm";

    onStatus({
      stage: "downloading",
      progress: null,
      detail: webgpu
        ? "Downloading the local language model"
        : "Downloading the local language model (CPU — no WebGPU on this browser)",
      device,
    });

    const { pipeline } = await loadRuntime();

    const seen = new Map<string, { loaded: number; total: number }>();

    const created = (await pipeline("text-generation", id, {
      /* q4f16 on WebGPU; q4 on WASM, where fp16 is not a win and is often
         unsupported. */
      dtype: webgpu ? "q4f16" : "q4",
      device,
      progress_callback: (report: unknown) => {
        const event = report as {
          status?: string;
          file?: string;
          loaded?: number;
          total?: number;
        };

        if (event.status === "progress" && event.file && event.total) {
          seen.set(event.file, {
            loaded: event.loaded ?? 0,
            total: event.total,
          });

          let loadedBytes = 0;
          let totalBytes = 0;
          for (const entry of seen.values()) {
            loadedBytes += entry.loaded;
            totalBytes += entry.total;
          }

          onStatus({
            stage: "downloading",
            progress: totalBytes > 0 ? Math.min(loadedBytes / totalBytes, 1) : null,
            detail: "Downloading the local language model",
            device,
          });
        }

        if (event.status === "ready" || event.status === "done") {
          onStatus({
            stage: "initialising",
            progress: 1,
            detail: webgpu ? "Starting WebGPU" : "Starting the CPU runtime",
            device,
          });
        }
      },
    })) as unknown as Generator;

    pipe = created;
    loadedId = id;
    onStatus({
      stage: "ready",
      progress: 1,
      detail: webgpu ? "Ready · running on WebGPU" : "Ready · running on CPU",
      device,
    });
    return created;
  })();

  try {
    return await loading;
  } catch (error) {
    pipe = null;
    loadedId = null;
    onStatus({
      stage: "failed",
      progress: null,
      /* Deliberately not the exception: the visitor is told what it means for
         them, and the assistant keeps working without it. */
      detail: "The local model could not be loaded. Answering from records.",
      device: null,
    });
    throw error;
  } finally {
    loading = null;
  }
}

/**
 * One grounded completion.
 *
 * The prompt is built by `prompt.ts` from retrieved records only, so this
 * function never decides what the model may know.
 */
export async function generate(
  system: string,
  user: string,
  signal?: AbortSignal,
): Promise<string> {
  if (!pipe) throw new Error("model not loaded");

  const output = await pipe(
    [
      { role: "system", content: system },
      { role: "user", content: user },
    ],
    { ...GENERATION, signal },
  );

  /* Transformers.js returns the full chat transcript; the answer is the last
     assistant turn, and its shape differs between chat and plain generation. */
  const text = output?.[0]?.generated_text;
  if (Array.isArray(text)) {
    const last = text[text.length - 1] as { content?: string } | undefined;
    return (last?.content ?? "").trim();
  }
  return typeof text === "string" ? text.trim() : "";
}
