import { GAIT_PHASES } from "@/components/visuals/gait-phases";
import { PoseFrame } from "@/components/research/PoseFrame";
import styles from "./gaitLabs.module.css";

/**
 * The two GaitAI Labs scenes: what a gait dataset IS, and what a gait
 * biometric IS. Both are drawn from the project's own stride keyframes
 * (`visuals/gait-phases.ts`) through the research page's `PoseFrame`, so a
 * walker here is provably the same anatomy as a walker on /research.
 *
 * NOTHING HERE IS A RESULT. The feature stack and the signature are
 * dimensionless illustrations generated by fixed functions; the only text in
 * either scene is a label. This repository holds no dataset statistics and no
 * recognition benchmarks, and a scene that printed one would be inventing it.
 */

const W = 760;
const H = 272;

const fig = {
  bone: styles.sBone,
  boneFar: styles.sBoneFar,
  joint: styles.sJoint,
  head: styles.sHead,
  contact: styles.sContact,
};

const r1 = (n: number) => Math.round(n * 10) / 10;

/** The five canonical gait events, as tick labels: "heel-strike" → "HEEL STRIKE". */
const phaseLabel = (id: string) => id.replace(/-/g, " ").toUpperCase();

/**
 * One temporal channel: a fixed, deterministic waveform so the stack is
 * identical on every render. `k` distinguishes the channels; nothing about
 * the curve is measured from anything.
 */
function channelPoints(k: number, x0: number, w: number, y0: number, amp: number) {
  const n = 56;
  return Array.from({ length: n }, (_, i) => {
    const t = i / (n - 1);
    const y =
      y0 +
      Math.sin(t * Math.PI * 2 * (1.5 + k * 0.5) + k * 0.9) *
        amp *
        (0.6 + 0.4 * Math.cos(t * 3 + k));
    return `${r1(x0 + t * w)},${r1(y)}`;
  }).join(" ");
}

/** Deterministic bar weight — a signature illustration, not a measurement. */
const weight = (i: number) =>
  Math.abs(Math.sin(i * 1.37 + 0.6) * 0.55 + Math.cos(i * 0.61) * 0.45);

const enter = (i: number) => ({
  className: styles.enter,
  style: { ["--s-i" as string]: i },
});

/* ── 01 · GAIT DATASET — sequence → record → lineage ─────────────────────── */

export function DatasetLineageScene() {
  const seqX = 16;
  const step = 40;
  const floorY = 150;

  return (
    <svg aria-hidden="true" viewBox={`0 0 ${W} ${H}`} className={styles.scene}>
      {/* ── the gait sequence: one stride at its five canonical events ── */}
      <text className={styles.sLabel} x={seqX} y={26}>
        GAIT SEQUENCE
      </text>
      {GAIT_PHASES.map((phase, i) => (
        <g key={phase.id} {...enter(i)}>
          <g transform={`translate(${seqX + 22 + i * step} ${floorY - 48})`}>
            <PoseFrame phase={phase} s={1} classes={fig} showContacts />
          </g>
        </g>
      ))}
      <line
        className={styles.sFloor}
        x1={seqX}
        y1={floorY + 1}
        x2={seqX + 24 + GAIT_PHASES.length * step}
        y2={floorY + 1}
      />

      {/* ── temporal gait phases, as ticks under the sequence ── */}
      <g {...enter(5)}>
        <line
          className={styles.sAxis}
          x1={seqX}
          y1={176}
          x2={seqX + 24 + GAIT_PHASES.length * step}
          y2={176}
        />
        {GAIT_PHASES.map((phase, i) => (
          <g key={phase.id}>
            <line
              className={styles.sTick}
              x1={seqX + 22 + i * step}
              y1={172}
              x2={seqX + 22 + i * step}
              y2={180}
            />
            <text
              className={styles.sDim}
              x={seqX + 22 + i * step}
              y={196}
              textAnchor="middle"
              transform={`rotate(-28 ${seqX + 22 + i * step} 196)`}
            >
              {phaseLabel(phase.id).split(" ")[0]}
            </text>
          </g>
        ))}
        <text className={styles.sDim} x={seqX} y={236}>
          TEMPORAL GAIT PHASES
        </text>
      </g>

      {/* ── flow → ── */}
      <g className={`${styles.sFlow} ${styles.enter}`} style={{ ["--s-i" as string]: 6 }}>
        <line x1={258} y1={112} x2={300} y2={112} />
        <polyline points="294,108 300,112 294,116" />
      </g>

      {/* ── the record: what one sequence becomes in the dataset ── */}
      <text className={styles.sLabel} x={312} y={26}>
        RECORD
      </text>
      <g {...enter(7)}>
        {/* Three stacked cards, offset, so the record reads as one of many. */}
        <rect className={styles.sRecord} x={326} y={66} width={150} height={92} rx={6} />
        <rect className={styles.sRecord} x={319} y={59} width={150} height={92} rx={6} />
        <rect className={styles.sRecord} x={312} y={52} width={150} height={92} rx={6} />
        {/* Field lines — a record has fields; none of them shows a value. */}
        {["SEQUENCE", "SUBJECT", "SESSION", "VIEW", "CONDITION"].map((field, i) => (
          <g key={field}>
            <text className={styles.sDim} x={326} y={74 + i * 14}>
              {field}
            </text>
            <line
              className={styles.sRecordLine}
              x1={392}
              y1={70.5 + i * 14}
              x2={392 + 26 + weight(i) * 28}
              y2={70.5 + i * 14}
            />
          </g>
        ))}
      </g>
      <text className={styles.sDim} x={312} y={176}>
        ONE SEQUENCE · ONE RECORD
      </text>

      {/* ── flow → ── */}
      <g className={`${styles.sFlow} ${styles.enter}`} style={{ ["--s-i" as string]: 8 }}>
        <line x1={486} y1={112} x2={528} y2={112} />
        <polyline points="522,108 528,112 522,116" />
      </g>

      {/* ── lineage: capture → protected → research use ── */}
      <text className={styles.sLabel} x={540} y={26}>
        DATA LINEAGE
      </text>
      <g {...enter(9)}>
        <circle className={styles.sNode} cx={556} cy={72} r={7} />
        <text className={styles.sDim} x={572} y={75}>
          CAPTURED
        </text>
        <line className={styles.sLinkProtected} x1={556} y1={80} x2={556} y2={104} />
        <circle className={styles.sNodeProtected} cx={556} cy={112} r={8} />
        <text className={styles.sDim} x={572} y={115}>
          IDENTITY PROTECTED
        </text>
        <line className={styles.sLink} x1={556} y1={121} x2={556} y2={144} />
        <circle className={styles.sNode} cx={556} cy={152} r={7} />
        <text className={styles.sDim} x={572} y={155}>
          RESEARCH USE
        </text>
        <line className={styles.sLink} x1={556} y1={160} x2={556} y2={184} />
        <circle className={styles.sNode} cx={556} cy={192} r={7} />
        <text className={styles.sDim} x={572} y={195}>
          CITED IN PUBLICATION
        </text>
      </g>
      <text className={styles.sDim} x={744} y={258} textAnchor="end">
        PROTECTED BEFORE IT IS USED
      </text>
    </svg>
  );
}

/* ── 02 · GAIT BIOMETRICS — stride → Motion DNA → signature → covariates ─── */

export function SignatureScene() {
  const channels = 5;
  const dnaX = 236;
  const dnaW = 196;
  const dnaTop = 58;
  const dnaGap = 26;

  return (
    <svg aria-hidden="true" viewBox={`0 0 ${W} ${H}`} className={styles.scene}>
      {/* ── the stride ── */}
      <text className={styles.sLabel} x={16} y={26}>
        ONE STRIDE
      </text>
      {[0, 2, 4].map((p, i) => (
        <g key={p} {...enter(i)}>
          <g transform={`translate(${44 + i * 56} 108)`}>
            <PoseFrame phase={GAIT_PHASES[p]} s={1.1} classes={fig} />
          </g>
        </g>
      ))}
      <line className={styles.sFloor} x1={16} y1={161} x2={200} y2={161} />
      <text className={styles.sDim} x={16} y={188}>
        SIDE VIEW · THREE EVENTS
      </text>

      {/* ── flow → ── */}
      <g className={`${styles.sFlow} ${styles.enter}`} style={{ ["--s-i" as string]: 3 }}>
        <line x1={196} y1={112} x2={226} y2={112} />
        <polyline points="220,108 226,112 220,116" />
      </g>

      {/* ── Motion DNA: the stride as a stack of temporal channels ── */}
      <text className={styles.sLabel} x={dnaX} y={26}>
        MOTION DNA
      </text>
      <g {...enter(4)}>
        {Array.from({ length: channels }, (_, k) => {
          const y0 = dnaTop + k * dnaGap;
          return (
            <g key={k}>
              <line
                className={styles.sChannelRule}
                x1={dnaX}
                y1={y0}
                x2={dnaX + dnaW}
                y2={y0}
              />
              <polyline
                className={styles.sChannel}
                style={{ ["--s-w" as string]: weight(k * 3).toFixed(3) }}
                points={channelPoints(k, dnaX, dnaW, y0, 8)}
              />
            </g>
          );
        })}
      </g>
      <text className={styles.sDim} x={dnaX} y={188}>
        TEMPORAL CHANNELS · TIME →
      </text>

      {/* ── flow → ── */}
      <g className={`${styles.sFlow} ${styles.enter}`} style={{ ["--s-i" as string]: 5 }}>
        <line x1={444} y1={112} x2={480} y2={112} />
        <polyline points="474,108 480,112 474,116" />
      </g>

      {/* ── the signature the channels collapse to ── */}
      <text className={styles.sLabel} x={494} y={26}>
        MOVEMENT SIGNATURE
      </text>
      <g className={`${styles.sSignature} ${styles.enter}`} style={{ ["--s-i" as string]: 6 }}>
        {Array.from({ length: 24 }, (_, i) => {
          const w = weight(i * 2);
          return (
            <line
              key={i}
              x1={500 + i * 6}
              y1={112 - w * 24}
              x2={500 + i * 6}
              y2={112 + w * 24}
            />
          );
        })}
      </g>
      <line className={styles.sAxis} x1={494} y1={112} x2={648} y2={112} />
      <text className={styles.sDim} x={494} y={188}>
        DIMENSIONLESS · NOT A SCORE
      </text>

      {/* ── covariates: what changes the walk without changing the walker ── */}
      {/* The four nodes sit on the ellipse's diagonals, clear of the flow
          arrow on the left and the signature's axis on the right. */}
      <g {...enter(7)}>
        <ellipse className={styles.sOrbit} cx={571} cy={112} rx={104} ry={56} />
        {[
          ["VIEW", 491, 76, "end", 483, 72],
          ["CLOTHING", 651, 76, "start", 659, 72],
          ["CARRYING", 491, 148, "end", 483, 158],
          ["SPEED", 651, 148, "start", 659, 158],
        ].map(([label, cx, cy, anchor, tx, ty]) => (
          <g key={label as string}>
            <circle
              className={styles.sOrbitNode}
              cx={cx as number}
              cy={cy as number}
              r={4.5}
            />
            <text
              className={styles.sDim}
              x={tx as number}
              y={ty as number}
              textAnchor={anchor as "start" | "end"}
            >
              {label}
            </text>
          </g>
        ))}
      </g>
      <text className={styles.sDim} x={744} y={258} textAnchor="end">
        COVARIATES ORBIT THE SIGNATURE
      </text>
    </svg>
  );
}

/** The scene for each GaitAI Labs asset, by record id. */
export const GAIT_LAB_SCENE: Record<string, () => React.ReactElement> = {
  dataset: DatasetLineageScene,
  biometrics: SignatureScene,
};
